### PR TITLE
Fixed crash when leaving Physics Sandbox

### LINKED ISSUE #5: Crash when closing window while in Physics Sandbox
```
Assertion failed!
File: ArkAngel/src/GameStateManager.cpp, Line 73
```

The call to `engine->ScriptEngine->RemoveConfigGroup(suid.c_str())` is failing because there are still references to the group.

### PR DESCRIPTION
**Pull request by apples**
Resolves #5

### CODE REVIEW

**Comment by xxAtrain223** [comment]
Not sure this fixes the issue, but rather avoids it... I'll merge the pull request tomorrow (10/31) if you haven't found a better solution.

**Comment by xxAtrain223** [comment]
At the moment, it's probably fine to just leave all of the types in the 'global namespace', but it would be nice to be able to unregister everything that we register.

**Comment by apples** [comment]
The issue is that a function in the "PhysicsSandbox" ConfigGroup depended on `b2body`, and you can't remove a ConfigGroup if things depend on it. Even though all the dependencies were inside the same ConfigGroup, AngelScript just sees "more than zero things depend on this ConfigGroup, cannot delete."

**Comment by xxAtrain223** [comment]
Do you think we could alter AngelScript to fix this bug?

**Pull request merged**
